import { PORTUGAL_TEAM_ID } from "@/lib/world-cup";
import { normalizeApiTeamName } from "@/lib/team-names";

/** Nome API-Football (inglês) → código circle-flags */
const TEAM_NAME_TO_FLAG: Record<string, string> = {
  USA: "us",
  "United States": "us",
  Canada: "ca",
  Mexico: "mx",
  Portugal: "pt",
  Spain: "es",
  France: "fr",
  England: "gb-eng",
  Germany: "de",
  Italy: "it",
  Netherlands: "nl",
  Belgium: "be",
  Croatia: "hr",
  Switzerland: "ch",
  Austria: "at",
  Denmark: "dk",
  Poland: "pl",
  Serbia: "rs",
  Ukraine: "ua",
  Scotland: "gb-sct",
  Wales: "gb-wls",
  Turkey: "tr",
  Türkiye: "tr",
  Sweden: "se",
  Norway: "no",
  "Czech Republic": "cz",
  Czechia: "cz",
  Hungary: "hu",
  Greece: "gr",
  Romania: "ro",
  "Republic of Ireland": "ie",
  Ireland: "ie",
  Slovakia: "sk",
  Slovenia: "si",
  Russia: "ru",
  Iceland: "is",
  Finland: "fi",
  Albania: "al",
  "North Macedonia": "mk",
  "Bosnia and Herzegovina": "ba",
  Georgia: "ge",
  Brazil: "br",
  Argentina: "ar",
  Uruguay: "uy",
  Colombia: "co",
  Chile: "cl",
  Peru: "pe",
  Ecuador: "ec",
  Paraguay: "py",
  Bolivia: "bo",
  Venezuela: "ve",
  Morocco: "ma",
  Senegal: "sn",
  Tunisia: "tn",
  Algeria: "dz",
  Egypt: "eg",
  Nigeria: "ng",
  Ghana: "gh",
  Cameroon: "cm",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  "South Africa": "za",
  Mali: "ml",
  "Burkina Faso": "bf",
  "DR Congo": "cd",
  "Congo DR": "cd",
  "Cape Verde": "cv",
  "Cape Verde Islands": "cv",
  Japan: "jp",
  "South Korea": "kr",
  "Korea Republic": "kr",
  Australia: "au",
  Iran: "ir",
  "IR Iran": "ir",
  "Saudi Arabia": "sa",
  Qatar: "qa",
  Iraq: "iq",
  "United Arab Emirates": "ae",
  Uzbekistan: "uz",
  Jordan: "jo",
  China: "cn",
  "China PR": "cn",
  "New Zealand": "nz",
  "Costa Rica": "cr",
  Panama: "pa",
  Honduras: "hn",
  Jamaica: "jm",
  Curacao: "cw",
  Curaçao: "cw",
  Haiti: "ht",
};

export function getTeamFlagCode(
  teamName: string,
  teamId?: number
): string | null {
  if (teamId === PORTUGAL_TEAM_ID) return "pt";
  const key = normalizeApiTeamName(teamName);
  return TEAM_NAME_TO_FLAG[key] ?? null;
}
